### ISSUE TITLE
`rake db:mongoid:create_indexes` fails on fresh install

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#167]
With a clean checkout of the twitarr codebase, following the README, the mongoid indexes command fails:

```
ranger@server3:~/git/twitarr$ rake db:mongoid:create_indexes
/home/ranger/cvs/twitarr/config/initializers/twitter.rb:3 warning: already initialized constant DEFAULT_OPTIONS
rake aborted!
NameError: uninitialized constant Forum::Searchable
/home/ranger/cvs/twitarr/app/models/forum.rb:3:in `Forum'
/home/ranger/cvs/twitarr/app/models/forum.rb:1:in `(root)'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/activesupport-4.1.8/lib/active_support/inflector/methods.rb:238:in `const_get'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/activesupport-4.1.8/lib/active_support/inflector/methods.rb:238:in `constantize'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/activesupport-4.1.8/lib/active_support/inflector/methods.rb:236:in `inject'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/activesupport-4.1.8/lib/active_support/inflector/methods.rb:236:in `constantize'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/activesupport-4.1.8/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/draper-1.4.0/lib/draper/decorator.rb:253:in `inferred_object_class'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/draper-1.4.0/lib/draper/decorator.rb:69:in `object_class'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/draper-1.4.0/lib/draper/decorator.rb:74:in `object_class?'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/draper-1.4.0/lib/draper/decorator.rb:243:in `alias_object_to_object_class_name'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/draper-1.4.0/lib/draper/decorator.rb:238:in `inherited'
/home/ranger/cvs/twitarr/app/decorators/forum_decorator.rb:1:in `load'
/home/ranger/cvs/twitarr/app/decorators/forum_decorator.rb:1:in `(root)'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/railties-4.1.8/lib/rails/engine.rb:468:in `each'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/railties-4.1.8/lib/rails/engine.rb:468:in `eager_load!'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/railties-4.1.8/lib/rails/engine.rb:467:in `eager_load!'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/railties-4.1.8/lib/rails/engine.rb:465:in `call'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/railties-4.1.8/lib/rails/engine.rb:465:in `eager_load!'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/mongoid-4.0.0/lib/mongoid/railties/database.rake:70:in `each'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/mongoid-4.0.0/lib/mongoid/railties/database.rake:70:in `(root)'
/home/ranger/.rvm/gems/jruby-1.7.18/bin/jruby_executable_hooks:15:in `eval'
/home/ranger/.rvm/gems/jruby-1.7.18/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => db:mongoid:create_indexes => db:mongoid:load_models
(See full trace by running task with --trace)
```

**Comment by RangerRick** [comment]
Environment:

* java 1.7.0_72
* jruby 1.7.18 (1.9.3p551)
* mongodb 2.0.6
* rails 4.1.8

**Comment by RangerRick** [comment]
I tried upgrading to mongodb 2.4.8 (latest in wheezy-backports) and I still get this failure on Debian.  On my Mac it runs fine.

**Comment by walkeriniraq** [comment]
I don't think it'll work without at least Mongo 2.6 - that's what I'm running. 2.6 was released at least a year ago, I think. The linux repos are waaaaay behind, which is why Mongo has its own repository:  http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian

**Comment by tasermonkey** [comment]
yeah, it worked on my precise64 vagrant vm.  But I just downloaded mongo from their site, and just unzipped it and run the binary from the zip. 

mongod -version
db version v2.6.6
2015-01-04T19:15:31.885+0000 git version: 608e8bc319627693b04cc7da29ecc300a5f45a1f

**Comment by tasermonkey** [comment]
I replicated the problem ... I had to recheck it out on a filesystem not shared with the mac

Then I proceeded to implement the fix:
https://github.com/walkeriniraq/twitarr/commit/167d09b21fe76d59e544ae6a4e1c699f71b84a4b

**Comment by RangerRick** [comment]
confirmed, works on both my debian system (with updated 2.6.6 mongodb) and my mac.
