### ISSUE TITLE
`rake db:seed` fails on fresh install

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#168]
On a fresh checkout of twitarr, following the instructions in the README, `rake db:seed` fails:

```
ranger@server3:~/git/twitarr$ rake db:seed
/home/ranger/cvs/twitarr/config/initializers/twitter.rb:3 warning: already initialized constant DEFAULT_OPTIONS
Using rails env development
Using a base date of 2015-01-03T16:39:31+00:00
rake aborted!
NameError: uninitialized constant User::Searchable
/home/ranger/cvs/twitarr/app/models/user.rb:5:in `User'
/home/ranger/cvs/twitarr/app/models/user.rb:3:in `(root)'
/home/ranger/cvs/twitarr/db/seeds.rb:6:in `load'
/home/ranger/cvs/twitarr/db/seeds.rb:6:in `(root)'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/mongoid-4.0.0/lib/mongoid/railties/database.rake:20:in `each'
/home/ranger/.rvm/gems/jruby-1.7.18/gems/mongoid-4.0.0/lib/mongoid/railties/database.rake:20:in `(root)'
/home/ranger/.rvm/gems/jruby-1.7.18/bin/jruby_executable_hooks:15:in `eval'
/home/ranger/.rvm/gems/jruby-1.7.18/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by RangerRick** [comment]
Environment:

* java 1.7.0_72
* jruby 1.7.18 (1.9.3p551)
* mongodb 2.0.6
* rails 4.1.8

**Comment by RangerRick** [comment]
Even on my mac (on which `rake db:mongoid:create_indexes` passes), this still fails for me with a different error:

```
Sin:~/git/twitarr ranger$ rake db:seed
/Users/ranger/rcs/twitarr/config/initializers/twitter.rb:4 warning: already initialized constant DEFAULT_OPTIONS
Using rails env development
Using a base date of 2015-01-03T11:54:07-05:00
Creating user kvort
rake aborted!
NameError: uninitialized constant UserController::ACTIVE_STATUS
/Users/ranger/rcs/twitarr/db/seeds.rb:8:in `(root)'
/Users/ranger/.rvm/gems/jruby-1.7.10/gems/mongoid-4.0.0/lib/mongoid/railties/database.rake:20:in `call'
/Users/ranger/.rvm/gems/jruby-1.7.10/gems/mongoid-4.0.0/lib/mongoid/railties/database.rake:20:in `(root)'
/Users/ranger/.rvm/gems/jruby-1.7.10/bin/jruby_executable_hooks:15:in `eval'
/Users/ranger/.rvm/gems/jruby-1.7.10/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by tasermonkey** [comment]
https://github.com/walkeriniraq/twitarr/commit/b3fc6bf2d2313dce486ef14df154a72f425c37b9 fixes this issue.

**Comment by RangerRick** [comment]
confirmed, works on both debian and mac
